export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';

export const REQUEST_BODY_STYLES = 'REQUEST_BODY_STYLES';
export const RECEIVE_BODY_STYLES = 'RECEIVE_BODY_STYLES';
