export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';

export const REQUEST_BODY_STYLES = 'REQUEST_BODY_STYLES';
export const RECEIVE_BODY_STYLES = 'RECEIVE_BODY_STYLES';

export const REQUEST_MARKS = 'REQUEST_MARKS';
export const RECEIVE_MARKS = 'RECEIVE_MARKS';

export const REQUEST_MODELS = 'REQUEST_MODELS';
export const RECEIVE_MODELS = 'RECEIVE_MODELS';

export const REQUEST_STATES = 'REQUEST_STATES';
export const RECEIVE_STATES = 'RECEIVE_STATES';
