export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const CLEAR_CATEGORY = 'CLEAR_CATEGORY';

export const SELECT_BODY_STYLE = 'SELECT_BODY_STYLE';
export const CLEAR_BODY_STYLE = 'CLEAR_BODY_STYLE';

export const SELECT_MARK = 'SELECT_MARK';
export const CLEAR_MARK = 'CLEAR_MARK';

export const SELECT_MODEL = 'SELECT_MODEL';
export const CLEAR_MODEL = 'CLEAR_MODEL';

export const SELECT_YEAR_RANGE = 'SELECT_YEAR_RANGE';
export const SELECT_MILEAGE_RANGE = 'SELECT_MILEAGE_RANGE';
