export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const CLEAR_CATEGORY = 'CLEAR_CATEGORY';

export const SELECT_BODY_STYLE = 'SELECT_BODY_STYLE';
export const CLEAR_BODY_STYLE = 'CLEAR_BODY_STYLE';

export const SELECT_MARK = 'SELECT_MARK';
export const CLEAR_MARK = 'CLEAR_MARK';

export const SELECT_MODEL = 'SELECT_MODEL';
export const CLEAR_MODEL = 'CLEAR_MODEL';

export const SELECT_YEAR_RANGE = 'SELECT_YEAR_RANGE';
export const SELECT_MILEAGE_RANGE = 'SELECT_MILEAGE_RANGE';

export const SELECT_STATE = 'SELECT_STATE';
export const CLEAR_STATE = 'CLEAR_STATE';

export const SELECT_GEARBOX = 'SELECT_GEARBOX';
export const CLEAR_GEARBOX = 'CLEAR_GEARBOX';

export const SELECT_FUEL = 'SELECT_FUEL';
export const CLEAR_FUEL = 'CLEAR_FUEL';